// Getters
export const KOMPANY_REQUEST = 'KOMPANY_REQUEST';
export const KOMPANY_SUCCESS = 'KOMPANY_SUCCESS';
export const KOMPANY_ERROR = 'KOMPANY_ERROR';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';