// Getters
export const KOMPANY_REQUEST = 'KOMPANY_REQUEST';
export const KOMPANY_SUCCESS = 'KOMPANY_SUCCESS';
export const KOMPANY_ERROR = 'KOMPANY_ERROR';

export const ICO_REQUEST = 'ICO_REQUEST';
export const ICO_SUCCESS = 'ICO_SUCCESS';
export const ICO_ERROR = 'ICO_ERROR';

export const KOMPANIES_REQUEST = 'KOMPANIES_REQUEST';
export const KOMPANIES_SUCCESS = 'KOMPANIES_SUCCESS';
export const KOMPANIES_ERROR = 'KOMPANIES_ERROR';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';